### ISSUE TITLE
Module "application" not found

### ISSUE THREAD

**Issue by rui-cruz** [NativeScript/sample-PhotoAlbum#9]
Hi,

I'm trying to see this demo in action, but app doesn't open after deploy.. I'm sure something is missing from me but this is all new for me..

here's the log:

BUILD SUCCESSFUL

Total time: 6.85 secs
Project successfully built
Using  C:\Users\Dev\nativescript\sample-PhotoAlbum\platforms\android\build\outputs\apk\samplePhotoAlbum-debug.apk
Successfully deployed on device with identifier 'LGD8552e0160bb'
--------- beginning of /dev/log/main
W/dalvikvm(17933): VFY: unable to find class referenced in signature ([Landroid/app/RemoteInput;)
E/dalvikvm(17933): Could not find class 'android.app.RemoteInput[]', referenced from method b.a
W/dalvikvm(17933): VFY: unable to resolve new-array 12802 ([Landroid/app/RemoteInput;) in Lb;
D/dalvikvm(17933): VFY: replacing opcode 0x23 at 0x0005
I/dalvikvm(17933): Could not find method android.transition.TransitionSet.getTransitionCount, referenced from method b.b
W/dalvikvm(17933): VFY: unable to resolve virtual method 5043: Landroid/transition/TransitionSet;.getTransitionCount ()I
D/dalvikvm(17933): VFY: replacing opcode 0x6e at 0x0009
D/dalvikvm(17933): DexOpt: unable to opt direct call 0x09d7 at 0x0e in Lb;.a
D/dalvikvm(17933): DexOpt: unable to opt direct call 0x0d4a at 0x0e in Lb;.a
D/dalvikvm(17933): DexOpt: unable to opt direct call 0x09d7 at 0x0e in Lb;.a
W/dalvikvm(17933): Unable to resolve superclass of Lbg; (785)
W/dalvikvm(17933): Link of class 'Lbg;' failed
D/dalvikvm(17933): DexOpt: unable to opt direct call 0x249a at 0x08 in Lb;.a
W/dalvikvm(17933): Unable to resolve superclass of Lbi; (785)
W/dalvikvm(17933): Link of class 'Lbi;' failed
D/dalvikvm(17933): DexOpt: unable to opt direct call 0x257c at 0x30 in Lb;.a
D/dalvikvm(17933): DexOpt: unable to opt direct call 0x0a2f at 0x13 in Lb;.a
I/dalvikvm(17933): Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method dvi.a
W/dalvikvm(17933): VFY: unable to resolve virtual method 2923: Landroid/content/pm/PackageManager;.getPackageInstaller ()Landroid/content/pm/PackageInstaller;
D/dalvikvm(17933): VFY: replacing opcode 0x6e at 0x000f
I/dalvikvm(17933): Could not find method android.app.Notification$Builder.setLocalOnly, referenced from method dvi.c
W/dalvikvm(17933): VFY: unable to resolve virtual method 2555: Landroid/app/Notification$Builder;.setLocalOnly (Z)Landroid/app/Notification$Builder;
D/dalvikvm(17933): VFY: replacing opcode 0x6e at 0x021b
D/dalvikvm(17933): Trying to load lib /data/app-lib/com.google.android.apps.plus-2/libcrashreporterer.so 0x4328b140
D/dalvikvm(17933): Added shared lib /data/app-lib/com.google.android.apps.plus-2/libcrashreporterer.so 0x4328b140
D/TNS.Native(17919): lenNodes=58116, lenNames=598636, lenValues=616285
D/TNS.Native(17919): time=6
D/TNS.Java(17919): port=-1
E/TNS.Native(17919): Error: Module "application" not found
E/TNS.Native(17919): File: "/data/data/org.nativescript.PhotoAlbumNativeCode/files/app/app.js, line: 0, column: 289
E/TNS.Native(17919): StackTrace: 
E/TNS.Native(17919): 	Frame: function:'require', file:'/data/data/org.nativescript.PhotoAlbumNativeCode/files/app/app.js', line: 2, column: 290
E/TNS.Native(17919): 	Frame: function:'', file:'/data/data/org.nativescript.PhotoAlbumNativeCode/files/app/app.js', line: 1, column: 19
W/System.err(17919): java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
W/System.err(17919): Error calling module function 
W/System.err(17919): Error: Module "application" not found
W/System.err(17919): File: "/data/data/org.nativescript.PhotoAlbumNativeCode/files/app/app.js, line: 0, column: 289
W/System.err(17919): StackTrace: 
W/System.err(17919): 	Frame: function:'require', file:'/data/data/org.nativescript.PhotoAlbumNativeCode/files/app/app.js', line: 2, column: 290
W/System.err(17919): 	Frame: function:'', file:'/data/data/org.nativescript.PhotoAlbumNativeCode/files/app/app.js', line: 1, column: 19
W/System.err(17919): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4433)
W/System.err(17919): 	at android.app.ActivityThread.access$1500(ActivityThread.java:142)
W/System.err(17919): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1263)
W/System.err(17919): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(17919): 	at android.os.Looper.loop(Looper.java:136)
W/System.err(17919): 	at android.app.ActivityThread.main(ActivityThread.java:5118)
W/System.err(17919): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(17919): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err(17919): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
W/System.err(17919): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
W/System.err(17919): 	at dalvik.system.NativeStart.main(Native Method)
W/System.err(17919): Caused by: com.tns.NativeScriptException: 
W/System.err(17919): Error calling module function 
W/System.err(17919): Error: Module "application" not found
W/System.err(17919): File: "/data/data/org.nativescript.PhotoAlbumNativeCode/files/app/app.js, line: 0, column: 289
W/System.err(17919): StackTrace: 
W/System.err(17919): 	Frame: function:'require', file:'/data/data/org.nativescript.PhotoAlbumNativeCode/files/app/app.js', line: 2, column: 290
W/System.err(17919): 	Frame: function:'', file:'/data/data/org.nativescript.PhotoAlbumNativeCode/files/app/app.js', line: 1, column: 19
W/System.err(17919): 	at com.tns.Platform.runNativeScript(Native Method)
W/System.err(17919): 	at com.tns.Platform.run(Platform.java:241)
W/System.err(17919): 	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:742)
W/System.err(17919): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
W/System.err(17919): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4430)
W/System.err(17919): 	... 10 more
I/Process (17919): Sending signal. PID: 17919 SIG: 9

**Comment by rui-cruz** [comment]
same behavior on other samples I'm trying.. what I'm doing wrong?

**Comment by rui-cruz** [comment]
ok... time to move on
